checkpoint_type: pretrained
checkpoint_path: ./checkpoint-50.pth

seed: 42
num_classes: 100
warmup_iter: 8000
use_jitter: false
train_print_freq: 50

lr: 0.0001
optim_mode: freeze
scheduler_gamma: 0.1
scheduler_step_size: 6

